[package]
name = "rustrover-high-load"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2.1.4"
diesel-async = { version = "0.4.1", features = ["postgres"] }
dotenvy = "0.15.7"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
